// REACT/iam-project-react/src/components/Navbar.js
import '../css/navbar.css';
import { Link } from 'react-router-dom';

const Navbar = () => {
    return ( 
    <div className="navbar-container">
        <ul className="app-navbar">
          <li className="navbar-link"><Link to="/">Home</Link></li>
          <li className="navbar-link"><Link to="/views">Views</Link></li>
          <li className="navbar-link"><Link to="/coverletter">Cover Letter</Link></li>
          <li className="navbar-link"><Link to="/certifications">Certifications</Link></li>
          <li className="navbar-link"><Link to="/repositories">Repositories</Link></li>
          <li className="navbar-link"><Link to="/applications">Applications</Link></li>
          <li className="navbar-link"><Link to="/testing">Testing</Link></li>
        </ul>
      </div>
    );
}
 
export default Navbar;

// VUE/iam-project-vue/src/components/Navbar.vue
<template>
    <div class="navbar-container">
      <ul class="app-navbar">
        <li class="navbar-link"><router-link to="/">Home</router-link></li>
        <li class="navbar-link"><router-link to="/views">Views</router-link></li>
        <li class="navbar-link"><router-link to="/coverletter">Cover Letter</router-link></li>
        <li class="navbar-link"><router-link to="/certifications">Certifications</router-link></li>
        <li class="navbar-link"><router-link to="/repositories">Repositories</router-link></li>
        <li class="navbar-link"><router-link to="/applications">Applications</router-link></li>
        <li class="navbar-link"><router-link to="/testing">Testing</router-link></li>
      </ul>
    </div>
</template>

<script>
export default {

}
</script>

<style scoped>
ul.app-navbar {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li.navbar-link {
  float: left;
}

li.navbar-link a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li.navbar-link a:hover {
  background-color: green;
}
</style>
