// REACT/iam-project-react/src/components/Navbar.js
import '../css/navbar.css';
import { Link } from 'react-router-dom';

const Navbar = () => {
    return ( 
    <div className="navbar-container">
        <ul className="app-navbar">
          <li className="navbar-link"><Link to="/">Home</Link></li>
          <li className="navbar-link"><Link to="/views">Views</Link></li>
          <li className="navbar-link"><Link to="/coverletter">Cover Letter</Link></li>
          <li className="navbar-link"><Link to="/certifications">Certifications</Link></li>
          <li className="navbar-link"><Link to="/repositories">Repositories</Link></li>
          <li className="navbar-link"><Link to="/applications">Applications</Link></li>
          <li className="navbar-link"><Link to="/testing">Testing</Link></li>
        </ul>
      </div>
    );
}
 
export default Navbar;

// ANGULAR/iam-project-angular/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterModule} from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

}

<div class="navbar-container">
  <ul class="app-navbar">
    <li class="navbar-link"><a [routerLink]="['/views']">Views</a></li>
    <li class="navbar-link" ><a [routerLink]="['/coverletter']">Cover Letter</a></li>
    <li class="navbar-link" ><a target="_blank" rel="noopener noreferrer" href="resume.pdf">Resume (PDF)</a></li>
    <li class="navbar-link" ><a [routerLink]="['/certifications']">Certifications</a></li>
    <li class="navbar-link" ><a [routerLink]="['/repositories']">Repositories</a></li>
    <li class="navbar-link" ><a [routerLink]="['/applications']">Applications</a></li>
    <li class="navbar-link" ><a [routerLink]="['/testing']">Testing</a></li>
  </ul>
</div>
<router-outlet />
